### ISSUE TITLE
Mobile device model need optimization

### ISSUE THREAD

**Issue by BruinY** [GetmeUK/ContentEdit#13]
Mobile devices can't normal in operation, the tool bar to cover the content area lead to problems such as inconvenient, hope to be able to attach importance to the use of mobile devices.thank you

**Comment by anthonyjb** [comment]
Hi @BruinY - unfortunately CE/CT doesn't support editing in mobile devices - a lot of stuff isn't designed to and wont work on mobiles. This is a long term goal but it's a long way off, quite possibly a v2 feature - in short a lot needs to change to support mobile and complete different UI would be required.

If you'd like to see support for mobile devices please consider adding an in issue to the CT issues to start the conversation with other devs :)
