### ISSUE TITLE
Strange key behaviour inside shadow dom

### ISSUE THREAD

**Issue by glromeo** [GetmeUK/ContentEdit#14]
The left key is not working, plus the enter inserts a section before rather than splitting the current.

It looks like my problem is that my [data-editable] is inside a #shadow-root

I the selection being always empty { 0, 0 } ...

**Comment by glromeo** [comment]
sorry, that was a red herring... clearly I have a problem with selection being always empty

I am putting together an example...

**Comment by glromeo** [comment]
it looks like my problem is that my [data-editable] is inside a #shadow-root

**Comment by glromeo** [comment]
`<!doctype html>
<html>
<head>
    <title>My page</title>
    <link rel="stylesheet" type="text/css" href="/lib/bower/ContentTools/build/content-tools.min.css">
    <style type="text/css">
        [data-editable] iframe,
        [data-editable] image,
        [data-editable] [data-ce-tag=img],
        [data-editable] img,
        [data-editable] video {
            clear: both;
            display: block;
            margin-left: auto;
            margin-right: auto;
            max-width: 100%;
        }

        [data-editable] .align-left {
            clear: initial;
            float: left;
            margin-right: 0.5em;
        }

        [data-editable].align-right {
            clear: initial;
            float: right;
            margin-left: 0.5em;
        }

        [data-editable] .text-center {
            text-align: center;
        }

        [data-editable] .text-left {
            text-align: left;
        }

        [data-editable] .text-right {
            text-align: right;
        }

        ​ .author {
            font-style: italic;
            font-weight: bold;
        }

        body {
            width: 100vw;
            height: 100vh;
        }

        custom-element {
            display: block;
        }
    </style>
</head>
<body>
<div class="my-editor-context">
    <custom-element id="customElement">
    </custom-element>
</div>
<script src="/lib/bower/ContentTools/build/content-tools.min.js"></script>
<script>
    window.addEventListener('load', function () {

        var shadowRoot = document.querySelector('#customElement').createShadowRoot();

        shadowRoot.innerHTML = document.querySelector('#template').textContent;

        var editor;
        ContentTools.StylePalette.add([
            new ContentTools.Style('Author', 'author', ['p'])
        ]);

        editor = ContentTools.EditorApp.get();
        editor.init('::shadow *[data-editable]', 'data-name');
    });
</script>
<script id="template" type="text/html">
    <div data-editable data-name="main-content">
        <blockquote>
            Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you
            live.
        </blockquote>
        <p>John F. Woods</p>
    </div>
</script>
</body>
</html>
`

**Comment by anthonyjb** [comment]
Hi @glromeo - I think this is probably an issue with [ContentSelect](https://github.com/GetmeUK/ContentSelect) and specifically the use of `window.getSelection().getRangeAt(0)` (see here https://github.com/GetmeUK/ContentSelect/blob/master/src/content-select.coffee#L98).

There's a discussion here: https://bugs.chromium.org/p/chromium/issues/detail?id=380690 on why this method wont behave as you might expect it to in a shadow DOM, and this specification from the W3C stating http://w3c.github.io/webcomponents/spec/shadow/#h-ranges-and-selections:

> Accordingly, selections may only exist within one node tree, because they are defined by a single range. The selection, returned by the window.getSelection() method never returns a selection within a shadow tree.

There's actually a similar issue if you try to edit content in an `iframe` when the editor is initialized in the main frame. 

So what's the solution? Well short term you could patch ContentSelect to allow the window object to be overridden and therefore allow you to set the shadow DOM root as the window object, or perhaps the easiest approach that might work is to load and initialize the editor within your shadow DOM as I believe in that case the window object will be set to shadow DOM for that code - but I haven't tried this so it's just a hunch.

Longer term I think we I'll add an enhancement / feature request for this issue to ContentSelect to see if there's a way we can automatically search other iframes and or shadow DOMs for selection within the document quickly.
