### ISSUE TITLE
Stop empty element <span> to be removed

### ISSUE THREAD

**Issue by turigeza** [GetmeUK/ContentEdit#16]
Hi,

Is there a way to stop an empty element being removed? An example would be Bootstrap icons
`
<span class="glyphicon glyphicon-download-alt"></span>
`
The above would be removed. This is of course the desired behaviour most of the time : ) But not in this case.

Btw you have done an great job ... I am so happy I found it : )

**Comment by anthonyjb** [comment]
Hi @turigeza,

That's a good question, I'm guessing the span is part of the contents of an editable text block. The HTMLString library used by ContentEdit to manage HTML editing uses a flat approach to as opposed to a tree structure approach, basically each character in the HTML string can have one or more tags associated with it, and if a tag spans multiple characters then each of those characters will be given that tag. This makes it possible to manage HTML more like it a string, which is great but it does have some limitations.

So how would we get around this :/ Well there are a couple of approaches you could try: 

- The cleanest for me would be to use CSS to hide the text inside the icon, so the icon would be `<span class="glyphicon glyphicon-download-alt">Download</span>` and then using CSS we could hide the inner text content, something along the lines of: `overflow: hidden; text-indent: 100%; white-space: nowrap;`
- You could insert a zero-width space (ZWSP) `&#8203;` inside the span or a `<wbr>` tag, this feels a little hacky though as it's not clear (certainly in the case of the ZWSP) what's going on.

I'll have a bit of a think on what other options might be possible but let me know if either of these does or doesn't work for you, happy to see if we can find a better solution.

**Comment by turigeza** [comment]
> I'm guessing the span is part of the contents of an editable text block.

Yes sorry if I didn't make that clear.

The first one for me makes the span expend 100% width.

Your second suggestion is nice one IMO. And it works good for now. Thank you. I didn't know about the zero-width space : ) I was going to insert a hidden span like `<span style="display:none">hidden</span>` if no other solution worked but `&#8203; `is much neater. 

I was thinking that you might already had a class or data attribute one can apply to the element for example <span data-empty> <span data-donotremoveifempty> etc .... which would not be removed  if empty.

I will use ZWSP for now 👍
