### ISSUE TITLE
How do I destroy/disable a Region ?

### ISSUE THREAD

**Issue by turigeza** [GetmeUK/ContentEdit#18]
Hi, 

Sorry to bother you with it but I am lost at how I can destroy or disable (maybe even better to disable) a Region.

So to explain I create an editable area like the following.

`
var region = new ContentEdit.Region( dom_el );
`

And now I would like to disable the editing on it or destroy the region. 

`
region.destroy();
region.disable();
`

I hoping to disable the editable area so that it is no longer editable. How would you do this ? 
The idea is that I can switch back and forth between editable and non-editable state.

I notice on you ContentTool demo here 
http://getcontenttools.com/demo
that you refresh the page when one clicks the red x on the top left.

I have also been here ...  
https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/editor.coffee#L284

Just to see how you might have dealt with it in ContentTools. But that doesn't seem to work for me ... nor I can fully understand it to be honest. 

Any thoughts on it maybe how I could achieve this? : ) 

Thank you ! : )

**Comment by anthonyjb** [comment]
Hi @turigeza,

So I refresh on CT to basically revert the content to it's previous state but you don't need to do that to disable editing of the region. There isn't a disable/destroy option but you can do the following to achieve that result:

```JavaScript
// Set a region as static HTML again
region.domElement().innerHTML = region.html();
```

Hope that's helpful :)

**Comment by turigeza** [comment]
Of course : ) 👍 . Thank you ! I have a go with it later on the week.

**Comment by turigeza** [comment]
Thank you for your help! Works great 👍
