### ISSUE TITLE
Font formatting

### ISSUE THREAD

**Issue by marzsocks** [GetmeUK/ContentEdit#21]
Any plans to add font formatting (family, color)? Or how does one go about doing this?

**Comment by aplblpsil** [comment]
/* NEW TOOL : FONT FAMILY  */

            ContentTools.FontFamilyDialog = (function(_super) {
                __extends(FontFamilyDialog, _super);

                function FontFamilyDialog(fontFamily) {
                    FontFamilyDialog.__super__.constructor.call(this);
                    fontFamily = $('.ct--puesdo-select').css('font-family');
                    this._fontFamily = fontFamily;
                    // alert(this._fontFamily);
                }

                FontFamilyDialog.prototype.mount = function() {
                    var tabFamilies, _domOption;

                    tabFamilies = ['-- Choisir --', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Impact', "\'Lucida Console\', Monaco, monospace", 
                    "\'Lucida Sans Unicode\', \'Lucida Grande\', sans-serif", "\'Palatino Linotype\', \'Book Antiqua\', Palatino, serif",
                    'Tahoma, Geneva, sans-serif', "\'Times New Roman\', Times, serif", 'Trebuchet MS', 'Verdana'];

                    FontFamilyDialog.__super__.mount.call(this);
                    this._domInput = document.createElement('select');
                    this._domInput.setAttribute('id', 'select-font-family');
                    this._domInput.setAttribute('name', 'select-font-family');
                    this._domInput.setAttribute('class', 'ct-anchored-dialog__input form-control');
                    for(var i = 0; i < tabFamilies.length; i++){
                        _domOption = document.createElement('option');
                        _domOption.setAttribute('id', 'font-family-option-' + [i]);
                        _domOption.setAttribute('name', 'font-family-option-' + [i]);
                        _domOption.setAttribute('value', tabFamilies[i]);
                        _domOption.setAttribute('style', 'font-family:' + tabFamilies[i] + ' !important;');
                        if(tabFamilies[i] == '-- Choisir --') {
                            _domOption.setAttribute('disabled', '');
                            if(this._fontFamily.match(/Roboto/)) {
                                _domOption.setAttribute('selected', 'selected');
                            }
                        }
                        
                        if(this._fontFamily == "\""+tabFamilies[i]+"\""){
                            _domOption.setAttribute('selected', 'selected');
                        }
                        if(this._fontFamily.replace(/\"/g, "\'") == tabFamilies[i]){
                            _domOption.setAttribute('selected', 'selected');
                        }
                        _domOption.appendChild(document.createTextNode(tabFamilies[i]));
                        
                        this._domInput.appendChild(_domOption);
                    }                
                    
                    this._domElement.appendChild(this._domInput);
                    
                    this._domButton = this.constructor.createDiv(['ct-anchored-dialog__button']);
                    this._domElement.appendChild(this._domButton);

                    return this._addDOMEventListeners();
                };

                FontFamilyDialog.prototype.save = function() {
                    var detail;
                    if (!this.isMounted()) {
                        this.dispatchEvent(this.createEvent('save'));
                        return;
                    }
                    detail = {
                        style: 'font-family:' + this._domInput.value.trim() + ';',
                        class: 'ct-added-fontFamily'
                    };
                    
                    return this.dispatchEvent(this.createEvent('save', detail));
                };

                FontFamilyDialog.prototype.show = function() {
                    FontFamilyDialog.__super__.show.call(this);
                        this._domInput.focus();
                        if (this._fontFamily) {
                            return this._domInput.style.fontFamily = this._fontFamily;
                        }
                };

                FontFamilyDialog.prototype.unmount = function() {
                    if (this.isMounted()) {
                        this._domInput.blur();
                    }
                    FontFamilyDialog.__super__.unmount.call(this);
                    this._domButton = null;
                    return this._domInput = null;
                };

                FontFamilyDialog.prototype._addDOMEventListeners = function() {
                    this._domInput.addEventListener('keypress', (function(_this) {
                        return function(ev) {
                            if (ev.keyCode === 13) {
                                return _this.save();
                            }
                        };
                    })(this));
                    this._domInput.addEventListener('change', (function(_this) {
                            $('body').on('change', '#select-font-family', function(){
                                var directFontFamilyChange = $(this).val();
                                $('.ct-anchored-dialog__input.form-control').css('font-family', directFontFamilyChange);
                                $('.ct--puesdo-select').css('font-family', directFontFamilyChange);
                            });

                    })(this));
                    return this._domButton.addEventListener('click', (function(_this) {
                        return function(ev) {
                            ev.preventDefault();
                            return _this.save();
                        };
                    })(this));
                };

                return FontFamilyDialog;

            })(ContentTools.AnchoredDialogUI);

            ContentTools.Tools.FontFamily = (function(_super) {
                __extends(FontFamily, _super);

                function FontFamily() {
                    return FontFamily.__super__.constructor.apply(this, arguments);
                }

                ContentTools.ToolShelf.stow(FontFamily, 'fontFamily');

                FontFamily.label = 'Font Family';

                FontFamily.icon = 'fontfamily';

                FontFamily.tagName = 'span';

                FontFamily.getAttr = function(attrName, element, selection) {
                    var c, from, selectedContent, tag, to, _i, _j, _len, _len1, _ref, _ref1, _ref2;
                    if (element.type() === 'Image') {
                        if (element.a) {
                            return element.a[attrName];
                        }
                    } else {
                        _ref = selection.get(), from = _ref[0], to = _ref[1];
                        selectedContent = element.content.slice(from, to);
                        _ref1 = selectedContent.characters;
                        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                            c = _ref1[_i];
                            if (!c.hasTags('span')) {
                                continue;
                            }
                            _ref2 = c.tags();
                            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
                                tag = _ref2[_j];
                                if (tag.name() === 'span') {
                                    return tag.attr(attrName);
                                }
                            }
                        }
                    }
                    return '';
                };

                FontFamily.canApply = function(element, selection) {
                    var character;

                    if (!element.content) {
                        return false;
                    }
                    if (!selection) {
                        return false;
                    }
                    if (selection.isCollapsed()) {
                        character = element.content.characters[selection.get()[0]];
                        if (!character || !character.hasTags('span')) {
                            return false;
                        }
                    }      
                    return true;
                    
                };

                FontFamily.isApplied = function(element, selection) {
                    if(this.getAttr('style', element, selection).match(/font-family/)){
                        return FontFamily.__super__.constructor.isApplied.call(this, element, selection);
                    }else{
                        return ;
                    }    
                };

                FontFamily.apply = function(element, selection, callback) {
                    var $puesdoSelect, allowScrolling, app, applied, characters, dialog, domElement, ends, from, measureSpan, modal, rect, scrollX, scrollY, selectTag, starts, to, toolDetail, transparent, _ref, _ref1;
                    toolDetail = {
                        'tool': this,
                        'element': element,
                        'selection': selection
                    };
                    if (!this.dispatchEditorEvent('tool-apply', toolDetail)) {
                        return;
                    }
                    applied = false;
                    
                    if (selection.isCollapsed()) {
                        characters = element.content.characters;
                        starts = selection.get(0)[0];
                        ends = starts;
                        while (starts > 0 && characters[starts - 1].hasTags('span')) {
                            starts -= 1;
                        }
                        while (ends < characters.length && characters[ends].hasTags('span')) {
                            ends += 1;
                        }
                        selection = new ContentSelect.Range(starts, ends);
                        selection.select(element.domElement());
                    }
                    element.storeState();
                    selectTag = new HTMLString.Tag('span', {
                        'class': 'ct--puesdo-select'
                    });
                    _ref = selection.get(), from = _ref[0], to = _ref[1];
                    element.content = element.content.format(from, to, selectTag);
                    element.updateInnerHTML();
                    domElement = element.domElement();
                    measureSpan = domElement.getElementsByClassName('ct--puesdo-select');
                    $puesdoSelect = $(measureSpan);
                    rect = measureSpan[0].getBoundingClientRect();
                    
                    app = ContentTools.EditorApp.get();
                    modal = new ContentTools.ModalUI(transparent = true, allowScrolling = true);
                    modal.addEventListener('click', function() {
                        this.unmount();
                        dialog.hide();
                        if (element.content) {
                            element.content = element.content.unformat(from, to, selectTag);
                            element.updateInnerHTML();
                            element.restoreState();
                        }
                        callback(applied);
                        if (applied) {
                            return ContentTools.Tools.FontFamily.dispatchEditorEvent('tool-applied', toolDetail);
                        }
                    });

                    dialog = new ContentTools.FontFamilyDialog(this.getAttr('style', element, selection));
                    _ref1 = ContentTools.getScrollPosition(), scrollX = _ref1[0], scrollY = _ref1[1];
                    dialog.position([rect.left + (rect.width / 2) + scrollX, rect.top + (rect.height / 2) + scrollY]);
                    dialog.addEventListener('save', function(ev) {
                        var detail, span, styleBefore;
                        detail = ev.detail();
                        applied = true;
                        element.content = element.content.unformat(from, to, 'span');
                        if (detail.style) {
                            if($puesdoSelect.parent().attr('style') != undefined){
                                styleBefore = $puesdoSelect.parent().attr('style');
                                if (!styleBefore.match(/font-family/)){
                                    span = new HTMLString.Tag('span', {'style' :  styleBefore + detail.style});
                                }else{  
                                    span = new HTMLString.Tag('span', {'style' : styleBefore.replace(/font-family:.+?;/, '') + detail.style});
                                }
                            }else{
                                styleBefore = $('.ct--puesdo-select').parent().closest('span').attr('style');
                                if(styleBefore != undefined){
                                    span = new HTMLString.Tag('span', {'style' : styleBefore.replace(/font-family:.+?;/, '') + detail.style});
                                }else{
                                    span = new HTMLString.Tag('span', {'style' : detail.style});
                                }
                            }
                            
                            element.content = element.content.format(from, to, span);
                            element.content.optimize();
                            
                        }
                        element.updateInnerHTML();
                       
                        element.taint();
                        return modal.dispatchEvent(modal.createEvent('click'));
                    });
                    app.attach(modal);
                    app.attach(dialog);
                    modal.show();
                    return dialog.show();
                };

                return FontFamily;

            })(ContentTools.Tools.Bold);

**Comment by aplblpsil** [comment]
And you can do the same for Color formatting.
Have a nice week-end

**Comment by anthonyjb** [comment]
@aplblpsil thanks for providing the solution your using here, I'm marking as invalid and closing purely because the issue belongs against content tools.
