### ISSUE TITLE
Region unusable after last element removed

### ISSUE THREAD

**Issue by magiksd** [GetmeUK/ContentEdit#28]
Hello,

When using multiple regions, and one region contains a single empty paragraph, clicking in another region remove the paragraph (because empty content), but then we can't click again to edit the region.

You should not remove an element if its region has only one child, maybe like this in [text.coffee](https://github.com/GetmeUK/ContentEdit/blob/master/src/scripts/text.coffee#L45) :
```
if @content.isWhitespace() and @can('remove')
    # Detatch element from parent if empty
    if @parent() and @parent().children.length > 1
        @parent().detach(this)
```

**Comment by anthonyjb** [comment]
@magiksd hey! - can you provide an example of this - I'm not aware that this is possible - by default the last element shouldn't be removed from a region and I've not come across this issue and I use the tool quite a bit. I did try to quickly replicate in the sandbox but wasn't able to reproduce sorry.

**Comment by magiksd** [comment]
I'm using ContentEdit directly with custom toolbar and tools, so I manage my own list of regions created by `new ContentEdit.Region`, maybe ContentTools manage it better and prevent removing last element of a region, because I can't reproduce the bug in the demo...

**Comment by anthonyjb** [comment]
@magiksd yeah so ContentTools by default listens for the removal of an element and then adds a default element to prevent regions becoming empty (if memory serves me correct).

**Comment by magiksd** [comment]
Yep, just found this while reading source code :

```
ContentEdit.Root.get().bind('detach', @_handleDetach)
```

...which calls `_preventEmptyRegions` to add <p> if necessary, so I have to implement same thing for my own editor

Sorry for this, thank you :)

**Comment by anthonyjb** [comment]
@magiksd :+1:
