### ISSUE TITLE
Holding shift does not highlight editable content in Firefox

### ISSUE THREAD

**Issue by nake89** [GetmeUK/ContentEdit#32]
I tested and it does work on Chromium, but not on Firefox. I'm using Linux (Manjaro).

**Comment by anthonyjb** [comment]
Hi @nake89 I'm using firefox 85.0 on linux (ubuntu 18) and the effect is working for me both on the demo page and on internal projects. Could you let me the know the version of firefox you are using please?

I don't have any easy way to test Linux (Manjaro) so I'm hoping it's a browser version issue I can reproduce!

**Comment by nake89** [comment]
I tested this on private browsing mode (known as incognito mode in Chrome) and it worked. So the culprit was one of my plugins (I don't use plugins in private mode). So I found out it was Vimium. I disabled Vimium on the example site and now it worked. Hopefully this helps somebody else.
