### ISSUE TITLE
Add `exports` to module

### ISSUE THREAD

**Issue by yaplusplus** [GetmeUK/ContentEdit#4]
Hey there, thanks for the great library!

Nice to see that it's on npm now. It would be also great to add possibilty to `require` it while making bundle with browserify or another CommonJS bundler (by exporting `ContentEdit` not only to the global scope but with `module.exports` too).

**Comment by anthonyjb** [comment]
Sure - thanks for the suggestion I'll look to do so for all CT libraries in the next release which will be some time next week :)
